name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: bogreolen_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ./backend/requirements.txt ]; then pip install -r ./backend/requirements.txt; fi

    - name: Wait for MySQL
      run: |
          echo "Waiting for MySQL to start..."
          for i in {1..20}; do
            if mysqladmin ping -h "127.0.0.1" -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready yet... retrying ($i/20)"
            sleep 5
          done

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      env:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: bogreolen_database
      run: |
        pytest ./backend/tests/basetests.py -v
